name: Run Scala Steward on the managed repositories

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Repository to update. Leave empty to update every repository managed by the GitHub App."
        required: false
        default: ""
  schedule:
    - cron: "0 5 1,15 * *"

jobs:
  get-repositories:
    name: Select repositories to update
    runs-on: ubuntu-latest
    outputs:
      repositories: ${{ steps.repositories.outputs.repositories }}
    steps:
      - name: Generate token
        id: github_app
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
        with:
          app_id: ${{ secrets.APP_ID }}
          installation_id: ${{ secrets.APP_INSTALLATION_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Select repositories to update
        id: repositories
        run: |
          if [ "${{ github.event.inputs.repository }}" != "" ]; then
            echo "repositories=[\"alejandrohdezma/${{ github.event.inputs.repository }}\"]" >> $GITHUB_OUTPUT
          else
            echo "repositories=$(gh api installation/repositories -q '.repositories | map(.full_name)')" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ steps.github_app.outputs.token }}

  run-scala-steward:
    name: ${{ matrix.repo }} - Dependency update
    runs-on: ubuntu-latest
    needs: get-repositories
    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson(needs.get-repositories.outputs.repositories) }}
    steps:
      - name: Checkout project
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Launch Scala Steward on ${{ matrix.repo }}
        uses: scala-steward-org/scala-steward-action@a5515d934b0dfb84f0ff6432ecc2bd6a57d13e70 # v2.50.0
        with:
          github-repository: ${{ matrix.repo }}
          github-app-auth-only: "true"
          github-app-id: ${{ secrets.APP_ID }}
          github-app-installation-id: ${{ secrets.APP_INSTALLATION_ID }}
          github-app-key: ${{ secrets.APP_PRIVATE_KEY }}
