name: Run Scala Steward on the managed repositories

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Repository to update. Leave empty to update every repository managed by the GitHub App."
        required: false
        default: ""
  schedule:
    - cron: "0 5 1,15 * *"

jobs:
  run-scala-steward-single-repository:
    name: Run Scala Steward in the selected repository
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.repository != ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Get the GitHub App installation token
        uses: alejandrohdezma/actions/github-app-token@v1
        id: github_app
        with:
          token: ${{ secrets.GH_APP_TOKEN }}

      - name: Launch Scala Steward in the selected repository
        uses: scala-steward-org/scala-steward-action@588b69dc8208157655226feeccb465350063cb55 # v2.36.0
        with:
          github-token: ${{ steps.github_app.outputs.token }}
          github-repository: alejandrohdezma/${{ github.event.inputs.repository }}
          author-email: 80571129+alejandrohdezma-steward[bot]@users.noreply.github.com
          author-name: alejandrohdezma-steward[bot]

  run-scala-steward-all-repos:
    name: Run Scala Steward in all the repositories managed by the GitHub App
    if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.repository == '')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Launch Scala Steward on all repositories managed by the Github App
        uses: scala-steward-org/scala-steward-action@snapshots/428
        with:
          github-app-id: ${{ secrets.APP_ID }}
          github-app-installation-id: ${{ secrets.APP_INSTALLATION_ID }}
          github-app-key: ${{ secrets.APP_PRIVATE_KEY }}
